name: __av__verinet

channels:
  - pytorch
  - conda-forge
  - nodefaults  # Explicitly block Anaconda repos

dependencies:
  # Critical pinned packages
  - python=3.9

  # Other conda packages (let conda resolve versions)
  - _libgcc_mutex
  - _openmp_mutex
  - ca-certificates
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip
  - readline
  - sqlite
  - tk
  - xz
  - zlib

# Pip dependencies (unchanged)
  - pip:
    - absl-py==1.4.0
    - astunparse==1.6.3
    - cachetools==5.3.1
    - configspace==0.7.1
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - cmake==3.26.4
    - coloredlogs==15.0.1
    - contourpy==1.1.0
    - cycler==0.11.0
    - dnnv==0.6.0
    - filelock==3.12.2
    - flatbuffers==2.0.7
    - fonttools==4.40.0
    - gast==0.4.0
    - google-auth==2.21.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.56.0
    - h5py==3.9.0
    - humanfriendly==10.0
    - idna==3.4
    - imageio==2.31.1
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - jinja2==3.1.2
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - lark==1.1.5
    - libclang==16.0.0
    - lit==16.0.6
    - markdown==3.4.3
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - netron==7.8.6
    - networkx==3.1
    - numpy==1.21.6
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - onnx==1.10.2
    - onnxruntime==1.15.1
    - opt-einsum==3.3.0
    - packaging==23.1
    - pillow==9.5.0
    - protobuf==3.19.6
    - psutil==5.9.5
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyparsing==3.1.0
    - python-dateutil==2.8.2
    - pywavelets==1.4.1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.18.3
    - scipy==1.10.1
    - setuptools==68.0.0
    - six==1.16.0
    - sympy==1.12
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - tensorflow==2.7.4
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - termcolor==2.3.0
    - tifffile==2023.4.12
    - torch==2.0.1
    - torchvision==0.15.2
    - tqdm==4.65.0
    - triton==2.0.0
    - typing-extensions==4.6.3
    - urllib3==1.26.16
    - werkzeug==2.3.6
    - wheel==0.40.0
    - wrapt==1.15.0
    - xpress==9.1.2
    - zipp==3.15.0
